# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/ping.proto\"%\n\x0fPingCodeRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\x1c\n\x0cPingCodeData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"Q\n\x10PingCodeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12 \n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\r.PingCodeDataH\x00\x88\x01\x01\x42\x07\n\x05_data\"(\n\x12PingMessageRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\"\n\x0fPingMessageData\x12\x0f\n\x07message\x18\x01 \x01(\t\"W\n\x13PingMessageResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12#\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x10.PingMessageDataH\x00\x88\x01\x01\x42\x07\n\x05_data2|\n\x0bPingService\x12\x31\n\x08PingCode\x12\x10.PingCodeRequest\x1a\x11.PingCodeResponse\"\x00\x12:\n\x0bPingMessage\x12\x13.PingMessageRequest\x1a\x14.PingMessageResponse\"\x00\x62\x06proto3')



_PINGCODEREQUEST = DESCRIPTOR.message_types_by_name['PingCodeRequest']
_PINGCODEDATA = DESCRIPTOR.message_types_by_name['PingCodeData']
_PINGCODERESPONSE = DESCRIPTOR.message_types_by_name['PingCodeResponse']
_PINGMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['PingMessageRequest']
_PINGMESSAGEDATA = DESCRIPTOR.message_types_by_name['PingMessageData']
_PINGMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['PingMessageResponse']
PingCodeRequest = _reflection.GeneratedProtocolMessageType('PingCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGCODEREQUEST,
  '__module__' : 'protos.ping_pb2'
  # @@protoc_insertion_point(class_scope:PingCodeRequest)
  })
_sym_db.RegisterMessage(PingCodeRequest)

PingCodeData = _reflection.GeneratedProtocolMessageType('PingCodeData', (_message.Message,), {
  'DESCRIPTOR' : _PINGCODEDATA,
  '__module__' : 'protos.ping_pb2'
  # @@protoc_insertion_point(class_scope:PingCodeData)
  })
_sym_db.RegisterMessage(PingCodeData)

PingCodeResponse = _reflection.GeneratedProtocolMessageType('PingCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGCODERESPONSE,
  '__module__' : 'protos.ping_pb2'
  # @@protoc_insertion_point(class_scope:PingCodeResponse)
  })
_sym_db.RegisterMessage(PingCodeResponse)

PingMessageRequest = _reflection.GeneratedProtocolMessageType('PingMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGMESSAGEREQUEST,
  '__module__' : 'protos.ping_pb2'
  # @@protoc_insertion_point(class_scope:PingMessageRequest)
  })
_sym_db.RegisterMessage(PingMessageRequest)

PingMessageData = _reflection.GeneratedProtocolMessageType('PingMessageData', (_message.Message,), {
  'DESCRIPTOR' : _PINGMESSAGEDATA,
  '__module__' : 'protos.ping_pb2'
  # @@protoc_insertion_point(class_scope:PingMessageData)
  })
_sym_db.RegisterMessage(PingMessageData)

PingMessageResponse = _reflection.GeneratedProtocolMessageType('PingMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGMESSAGERESPONSE,
  '__module__' : 'protos.ping_pb2'
  # @@protoc_insertion_point(class_scope:PingMessageResponse)
  })
_sym_db.RegisterMessage(PingMessageResponse)

_PINGSERVICE = DESCRIPTOR.services_by_name['PingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGCODEREQUEST._serialized_start=21
  _PINGCODEREQUEST._serialized_end=58
  _PINGCODEDATA._serialized_start=60
  _PINGCODEDATA._serialized_end=88
  _PINGCODERESPONSE._serialized_start=90
  _PINGCODERESPONSE._serialized_end=171
  _PINGMESSAGEREQUEST._serialized_start=173
  _PINGMESSAGEREQUEST._serialized_end=213
  _PINGMESSAGEDATA._serialized_start=215
  _PINGMESSAGEDATA._serialized_end=249
  _PINGMESSAGERESPONSE._serialized_start=251
  _PINGMESSAGERESPONSE._serialized_end=338
  _PINGSERVICE._serialized_start=340
  _PINGSERVICE._serialized_end=464
# @@protoc_insertion_point(module_scope)
